package pe.gob.sunat.service.consult;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.5
 * 2015-10-29T20:46:42.619+01:00
 * Generated source version: 3.0.5
 */
@WebService(targetNamespace = "http://service.sunat.gob.pe", name = "billService")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface BillService {

    @WebMethod(action = "urn:getStatus")
    @WebResult(name = "status", targetNamespace = "")
    @RequestWrapper(localName = "getStatus", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.service.consult.GetStatus")
    @ResponseWrapper(localName = "getStatusResponse", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.service.consult.GetStatusResponse")
    public StatusResponse getStatus(@WebParam(name = "rucComprobante", targetNamespace = "") String rucComprobante, @WebParam(name = "tipoComprobante", targetNamespace = "") String tipoComprobante, @WebParam(name = "serieComprobante", targetNamespace = "") String serieComprobante, @WebParam(name = "numeroComprobante", targetNamespace = "") Integer numeroComprobante);

    @WebMethod(action = "urn:getStatusCdr")
    @WebResult(name = "statusCdr", targetNamespace = "")
    @RequestWrapper(localName = "getStatusCdr", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.service.consult.GetStatusCdr")
    @ResponseWrapper(localName = "getStatusCdrResponse", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.service.consult.GetStatusCdrResponse")
    public StatusResponse getStatusCdr(@WebParam(name = "rucComprobante", targetNamespace = "") String rucComprobante, @WebParam(name = "tipoComprobante", targetNamespace = "") String tipoComprobante, @WebParam(name = "serieComprobante", targetNamespace = "") String serieComprobante, @WebParam(name = "numeroComprobante", targetNamespace = "") Integer numeroComprobante);

} //BillService
