//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.03 at 02:03:31 PM PET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:sunat:names:specification:ubl:peru:schema:xsd:SunatAggregateComponents-1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED, xmlns={@javax.xml.bind.annotation.XmlNs(namespaceURI="urn:sunat:names:specification:ubl:peru:schema:xsd:SunatAggregateComponents-1", prefix="sac")})
package sunat.names.specification.ubl.peru.schema.xsd.sunataggregatecomponents_1;
