package pe.gob.sunat.serviceFE;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2020-04-19T22:14:08.664-05:00
 * Generated source version: 3.3.2
 */
@WebServiceClient(name = "billService",
        wsdlLocation = "https://e-beta.sunat.gob.pe/ol-ti-itcpfegem-beta/billService?wsdl",
        targetNamespace = "http://service.gem.factura.comppago.registro.servicio.sunat.gob.pe/")
public class BillServiceImpl extends Service {

    public final static QName SERVICE = new QName("http://service.gem.factura.comppago.registro.servicio.sunat.gob.pe/", "billService");

    public final static QName BillServicePort3 = new QName("http://service.gem.factura.comppago.registro.servicio.sunat.gob.pe/", "BillServicePort.3");

    public final static QName BillServicePort0 = new QName("http://service.gem.factura.comppago.registro.servicio.sunat.gob.pe/", "BillServicePort.0");

    public final static QName BillServicePort = new QName("http://service.gem.factura.comppago.registro.servicio.sunat.gob.pe/", "BillServicePort");

    public BillServiceImpl(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BillServiceImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BillServiceImpl(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public BillServiceImpl(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns BillService
     */
    @WebEndpoint(name = "BillServicePort.3")
    public BillService getBillServicePort3() {
        return super.getPort(BillServicePort3, BillService.class);
    }

    /**
     * @param features A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns BillService
     */
    @WebEndpoint(name = "BillServicePort.3")
    public BillService getBillServicePort3(WebServiceFeature... features) {
        return super.getPort(BillServicePort3, BillService.class, features);
    }


    /**
     * @return returns BillService
     */
    @WebEndpoint(name = "BillServicePort.0")
    public BillService getBillServicePort0() {
        return super.getPort(BillServicePort0, BillService.class);
    }

    /**
     * @param features A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns BillService
     */
    @WebEndpoint(name = "BillServicePort.0")
    public BillService getBillServicePort0(WebServiceFeature... features) {
        return super.getPort(BillServicePort0, BillService.class, features);
    }

    /**
     * @return returns BillService
     */
    @WebEndpoint(name = "BillServicePort")
    public BillService getBillServicePort() {
        return super.getPort(BillServicePort, BillService.class);
    }

    /**
     * @param features A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns BillService
     */
    @WebEndpoint(name = "BillServicePort")
    public BillService getBillServicePort(WebServiceFeature... features) {
        return super.getPort(BillServicePort, BillService.class, features);
    }

}
