//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.19 at 09:27:25 AM COT 
//


package un.unece.uncefact.data.specification.unqualifieddatatypesschemamodule._2;

import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.*;
import oasis.names.specification.ubl.schema.xsd.commonextensioncomponents_2.ExtensionReasonCodeType;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:UniqueID xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;UBLUDT000007&lt;/ccts:UniqueID&gt;
 * </pre>
 *
 *
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:CategoryCode xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;UDT&lt;/ccts:CategoryCode&gt;
 * </pre>
 *
 *
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:DictionaryEntryName xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Code. Type&lt;/ccts:DictionaryEntryName&gt;
 * </pre>
 *
 *
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:VersionID xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;1.0&lt;/ccts:VersionID&gt;
 * </pre>
 *
 *
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Definition xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;A character string (letters, figures, or symbols) that for brevity and/or languange independence may be used to represent or replace a definitive value or text of an attribute together with relevant supplementary information.&lt;/ccts:Definition&gt;
 * </pre>
 *
 *
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:RepresentationTermName xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Code&lt;/ccts:RepresentationTermName&gt;
 * </pre>
 *
 *
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:PrimitiveType xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;string&lt;/ccts:PrimitiveType&gt;
 * </pre>
 *
 *
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:UsageRule xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Other supplementary components in the CCT are captured as part of the token and name for the schema module containing the code list and thus, are not declared as attributes. &lt;/ccts:UsageRule&gt;
 * </pre>
 *
 *
 *
 * <p>Java class for CodeType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="CodeType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2>CodeType">
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CodeType")
@XmlSeeAlso({
        IndustryClassificationCodeType.class,
        TariffClassCodeType.class,
        CustomsStatusCodeType.class,
        PerformanceMetricTypeCodeType.class,
        NameCodeType.class,
        AccountingCostCodeType.class,
        RejectActionCodeType.class,
        IdentificationCodeType.class,
        AddressFormatCodeType.class,
        RequestedInvoiceCurrencyCodeType.class,
        InspectionMethodCodeType.class,
        HeatingTypeCodeType.class,
        DescriptionCodeType.class,
        ExpenseCodeType.class,
        CardChipCodeType.class,
        TimingComplaintCodeType.class,
        ContractingPartyTypeCodeType.class,
        CardTypeCodeType.class,
        AwardingMethodTypeCodeType.class,
        CollaborationPriorityCodeType.class,
        MandateTypeCodeType.class,
        ReferenceEventCodeType.class,
        ConditionCodeType.class,
        QuantityDiscrepancyCodeType.class,
        EmergencyProceduresCodeType.class,
        ExecutionRequirementCodeType.class,
        PackLevelCodeType.class,
        LatitudeDirectionCodeType.class,
        SubTypeCodeType.class,
        ParentDocumentTypeCodeType.class,
        ResidenceTypeCodeType.class,
        ConsumptionTypeCodeType.class,
        AwardingCriteriaTypeCodeType.class,
        ExemptionReasonCodeType.class,
        PartPresentationCodeType.class,
        EvidenceTypeCodeType.class,
        SealStatusCodeType.class,
        ConsumptionLevelCodeType.class,
        CorrectionTypeCodeType.class,
        FreightRateClassCodeType.class,
        EvaluationCriteriaTypeCodeType.class,
        PurposeCodeType.class,
        AccountTypeCodeType.class,
        UNDGCodeType.class,
        ReasonCodeType.class,
        HazardousCategoryCodeType.class,
        ResultCodeType.class,
        TariffCodeType.class,
        MeterReadingTypeCodeType.class,
        TransportEquipmentTypeCodeType.class,
        RejectReasonCodeType.class,
        TelecommunicationsServiceCategoryCodeType.class,
        TradeItemPackingLabelingTypeCodeType.class,
        ResponseCodeType.class,
        DirectionCodeType.class,
        TenderEnvelopeTypeCodeType.class,
        TenderTypeCodeType.class,
        PaymentChannelCodeType.class,
        SubmissionMethodCodeType.class,
        PromotionalEventTypeCodeType.class,
        SubstitutionStatusCodeType.class,
        HazardousRegulationCodeType.class,
        AdjustmentReasonCodeType.class,
        UrgencyCodeType.class,
        CorporateRegistrationTypeCodeType.class,
        SourceCurrencyCodeType.class,
        TransportServiceCodeType.class,
        StatusReasonCodeType.class,
        TransportEventTypeCodeType.class,
        ServiceTypeCodeType.class,
        TransportAuthorizationCodeType.class,
        ShippingPriorityLevelCodeType.class,
        PaymentPurposeCodeType.class,
        ComparisonDataCodeType.class,
        ClauseCodeType.class,
        MiscellaneousEventTypeCodeType.class,
        ExpressionCodeType.class,
        SealIssuerTypeCodeType.class,
        ProviderTypeCodeType.class,
        DispositionCodeType.class,
        LifeCycleStatusCodeType.class,
        TaxLevelCodeType.class,
        ActivityCodeType.class,
        FeatureTacticTypeCodeType.class,
        OperationStatusCodeType.class,
        PaymentMeansCodeType.class,
        TelecommunicationsSupplyTypeCodeType.class,
        TelecommunicationsServiceCallCodeType.class,
        QualityControlCodeType.class,
        DeclarationTypeCodeType.class,
        EnergyWaterSupplyCodeType.class,
        PriceEvaluationCodeType.class,
        AccountFormatCodeType.class,
        PrivacyCodeType.class,
        TaxTypeCodeType.class,
        PreferenceCriterionCodeType.class,
        CertificateTypeCodeType.class,
        LocationTypeCodeType.class,
        EncodingCodeType.class,
        TransportEmergencyCardCodeType.class,
        ForecastPurposeCodeType.class,
        TimeFrequencyCodeType.class,
        PaymentAlternativeCurrencyCodeType.class,
        ExceptionStatusCodeType.class,
        RetailEventStatusCodeType.class,
        GuaranteeTypeCodeType.class,
        TransportMeansTypeCodeType.class,
        SupplyChainActivityTypeCodeType.class,
        StatusCodeType.class,
        DespatchAdviceTypeCodeType.class,
        LineStatusCodeType.class,
        ContractingSystemCodeType.class,
        CalculationExpressionCodeType.class,
        LongitudeDirectionCodeType.class,
        ConsumerIncentiveTacticTypeCodeType.class,
        PreviousCancellationReasonCodeType.class,
        FormatCodeType.class,
        DisplayTacticTypeCodeType.class,
        ConstitutionCodeType.class,
        TaxCurrencyCodeType.class,
        CurrencyCodeType.class,
        CountrySubentityCodeType.class,
        TaxExemptionReasonCodeType.class,
        ComparisonDataSourceCodeType.class,
        ActionCodeType.class,
        ResolutionCodeType.class,
        PackageLevelCodeType.class,
        HandlingCodeType.class,
        DocumentTypeCodeType.class,
        ForecastTypeCodeType.class,
        PackagingTypeCodeType.class,
        OrderResponseCodeType.class,
        NatureCodeType.class,
        LocaleCodeType.class,
        OwnerTypeCodeType.class,
        PricingCurrencyCodeType.class,
        ContractTypeCodeType.class,
        CapabilityTypeCodeType.class,
        ProfileStatusCodeType.class,
        TendererRequirementTypeCodeType.class,
        ShortageActionCodeType.class,
        ReminderTypeCodeType.class,
        AvailabilityStatusCodeType.class,
        FinancingInstrumentCodeType.class,
        CommodityCodeType.class,
        OrderTypeCodeType.class,
        ApplicationStatusCodeType.class,
        CargoTypeCodeType.class,
        ConsumersEnergyLevelCodeType.class,
        SubscriberIDTypeCodeType.class,
        CurrentChargeTypeCodeType.class,
        CoordinateSystemCodeType.class,
        TargetCurrencyCodeType.class,
        AdmissionCodeType.class,
        InhalationToxicityZoneCodeType.class,
        MeterConstantCodeType.class,
        MathematicOperatorCodeType.class,
        SubscriberTypeCodeType.class,
        DutyCodeType.class,
        TypeCodeType.class,
        AllowanceChargeReasonCodeType.class,
        InvoiceTypeCodeType.class,
        ChannelCodeType.class,
        ThresholdValueComparisonCodeType.class,
        ItemClassificationCodeType.class,
        MeterReadingMethodCodeType.class,
        UtilityStatementTypeCodeType.class,
        RevisionStatusCodeType.class,
        DataSourceCodeType.class,
        WeightingAlgorithmCodeType.class,
        ProcedureCodeType.class,
        SizeTypeCodeType.class,
        AddressTypeCodeType.class,
        RoleCodeType.class,
        TransportHandlingUnitTypeCodeType.class,
        FullnessIndicationCodeType.class,
        LossRiskResponsibilityCodeType.class,
        TrackingDeviceCodeType.class,
        CompanyLiquidationStatusCodeType.class,
        CompanyTypeCodeType.class,
        TransportModeCodeType.class,
        MimeCodeType.class,
        PaymentCurrencyCodeType.class,
        SecurityClassificationCodeType.class,
        ImportanceCodeType.class,
        DocumentStatusCodeType.class,
        MedicalFirstAidGuideCodeType.class,
        TradeServiceCodeType.class,
        PackingCriteriaCodeType.class,
        PriceTypeCodeType.class,
        OneTimeChargeTypeCodeType.class,
        PaymentFrequencyCodeType.class,
        DocumentCurrencyCodeType.class,
        PositionCodeType.class,
        FundingProgramCodeType.class,
        TransitDirectionCodeType.class,
        CharacterSetCodeType.class,
        ExtensionReasonCodeType.class
})
public class CodeType
        extends un.unece.uncefact.data.specification.corecomponenttypeschemamodule._2.CodeType {


}
