//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.19 at 09:27:25 AM COT 
//


package un.unece.uncefact.data.specification.unqualifieddatatypesschemamodule._2;

import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.*;
import oasis.names.specification.ubl.schema.xsd.commonextensioncomponents_2.ExtensionAgencyIDType;
import oasis.names.specification.ubl.schema.xsd.commonextensioncomponents_2.ExtensionAgencyURIType;
import oasis.names.specification.ubl.schema.xsd.commonextensioncomponents_2.ExtensionURIType;
import oasis.names.specification.ubl.schema.xsd.commonextensioncomponents_2.ExtensionVersionIDType;
import oasis.names.specification.ubl.schema.xsd.signaturebasiccomponents_2.ReferencedSignatureIDType;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:UniqueID xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;UBLUDT0000011&lt;/ccts:UniqueID&gt;
 * </pre>
 *
 *
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:CategoryCode xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;UDT&lt;/ccts:CategoryCode&gt;
 * </pre>
 *
 *
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:DictionaryEntryName xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Identifier. Type&lt;/ccts:DictionaryEntryName&gt;
 * </pre>
 *
 *
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:VersionID xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;1.0&lt;/ccts:VersionID&gt;
 * </pre>
 *
 *
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Definition xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;A character string to identify and distinguish uniquely, one instance of an object in an identification scheme from all other objects in the same scheme together with relevant supplementary information.&lt;/ccts:Definition&gt;
 * </pre>
 *
 *
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:RepresentationTermName xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Identifier&lt;/ccts:RepresentationTermName&gt;
 * </pre>
 *
 *
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:PrimitiveType xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;string&lt;/ccts:PrimitiveType&gt;
 * </pre>
 *
 *
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:UsageRule xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Other supplementary components in the CCT are captured as part of the token and name for the schema module containing the identifer list and thus, are not declared as attributes. &lt;/ccts:UsageRule&gt;
 * </pre>
 *
 *
 *
 * <p>Java class for IdentifierType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="IdentifierType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2>IdentifierType">
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IdentifierType")
@XmlSeeAlso({
        ContractFolderIDType.class,
        SalesOrderIDType.class,
        TrackingIDType.class,
        ChipApplicationIDType.class,
        UBLVersionIDType.class,
        AwardingCriteriaIDType.class,
        UUIDType.class,
        ContractedCarrierAssignedIDType.class,
        SalesOrderLineIDType.class,
        InformationURIType.class,
        SequenceNumberIDType.class,
        PrepaidPaymentReferenceIDType.class,
        AuctionURIType.class,
        IDType.class,
        JourneyIDType.class,
        CustomizationIDType.class,
        ReferencedConsignmentIDType.class,
        LoadingSequenceIDType.class,
        BuyerEventIDType.class,
        RegistrationIDType.class,
        ExchangeMarketIDType.class,
        BusinessIdentityEvidenceIDType.class,
        AccountIDType.class,
        PrimaryAccountNumberIDType.class,
        SecurityIDType.class,
        ImmobilizationCertificateIDType.class,
        RequiredCustomsIDType.class,
        RailCarIDType.class,
        WebsiteURIType.class,
        UpperOrangeHazardPlacardIDType.class,
        BusinessClassificationEvidenceIDType.class,
        ExtendedIDType.class,
        MarkingIDType.class,
        DocumentIDType.class,
        PaymentIDType.class,
        SuccessiveSequenceIDType.class,
        BuyerProfileURIType.class,
        LanguageIDType.class,
        SerialIDType.class,
        OriginalJobIDType.class,
        VersionIDType.class,
        RegistrationNationalityIDType.class,
        LocationIDType.class,
        EvidenceSuppliedIDType.class,
        ProcurementProjectLotIDType.class,
        IdentificationIDType.class,
        OriginalContractingSystemIDType.class,
        NetworkIDType.class,
        SpecificationIDType.class,
        ConsumptionReportIDType.class,
        LicensePlateIDType.class,
        LotNumberIDType.class,
        PaymentMeansIDType.class,
        AttributeIDType.class,
        PerformingCarrierAssignedIDType.class,
        ProfileIDType.class,
        ConsignorAssignedIDType.class,
        LineIDType.class,
        SubscriberIDType.class,
        BrokerAssignedIDType.class,
        TransportationServiceDetailsURIType.class,
        EnergyWaterSupplyIDType.class,
        PreviousJobIDType.class,
        AircraftIDType.class,
        RequestForQuotationLineIDType.class,
        SupplierAssignedAccountIDType.class,
        ParentDocumentIDType.class,
        CV2IDType.class,
        ConsigneeAssignedIDType.class,
        PreviousVersionIDType.class,
        FreightForwarderAssignedIDType.class,
        ProfileExecutionIDType.class,
        SignatureIDType.class,
        EndpointIDType.class,
        ValidatorIDType.class,
        CustomerAssignedAccountIDType.class,
        InstructionIDType.class,
        IssuerIDType.class,
        ShippingOrderIDType.class,
        OpenTenderIDType.class,
        TrainIDType.class,
        SchemeURIType.class,
        LowerOrangeHazardPlacardIDType.class,
        TraceIDType.class,
        TenderEnvelopeIDType.class,
        VesselIDType.class,
        ReferenceIDType.class,
        RevisedForecastLineIDType.class,
        SellerEventIDType.class,
        CarrierAssignedIDType.class,
        ParentDocumentLineReferenceIDType.class,
        URIType.class,
        AgencyIDType.class,
        CompanyIDType.class,
        InterestedProcurementLotsIDType.class,
        SequenceIDType.class,
        VariantIDType.class,
        HazardClassIDType.class,
        AdditionalAccountIDType.class,
        OntologyURIType.class,
        LogoReferenceIDType.class,
        EconomicOperatorRegistryURIType.class,
        ProductTraceIDType.class,
        IssueNumberIDType.class,
        ExtensionAgencyIDType.class,
        ExtensionAgencyURIType.class,
        ExtensionVersionIDType.class,
        ExtensionURIType.class,
        ReferencedSignatureIDType.class
})
public class IdentifierType
        extends un.unece.uncefact.data.specification.corecomponenttypeschemamodule._2.IdentifierType {


}
