//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.19 at 09:27:25 AM COT 
//


package un.unece.uncefact.data.specification.unqualifieddatatypesschemamodule._2;

import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.*;

import javax.xml.bind.annotation.*;


/**
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:UniqueID xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;UBLUDT0000012&lt;/ccts:UniqueID&gt;
 * </pre>
 *
 *
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:CategoryCode xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;UDT&lt;/ccts:CategoryCode&gt;
 * </pre>
 *
 *
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:DictionaryEntryName xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Indicator. Type&lt;/ccts:DictionaryEntryName&gt;
 * </pre>
 *
 *
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:VersionID xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;1.0&lt;/ccts:VersionID&gt;
 * </pre>
 *
 *
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Definition xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;A list of two mutually exclusive Boolean values that express the only possible states of a property.&lt;/ccts:Definition&gt;
 * </pre>
 *
 *
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:RepresentationTermName xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Indicator&lt;/ccts:RepresentationTermName&gt;
 * </pre>
 *
 *
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:PrimitiveType xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;string&lt;/ccts:PrimitiveType&gt;
 * </pre>
 *
 *
 *
 * <p>Java class for IndicatorType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="IndicatorType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>boolean">
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IndicatorType", propOrder = {
        "value"
})
@XmlSeeAlso({
        OptionalLineItemIndicatorType.class,
        VariantConstraintIndicatorType.class,
        RefrigeratedIndicatorType.class,
        CompletionIndicatorType.class,
        LegalStatusIndicatorType.class,
        LivestockIndicatorType.class,
        FreeOfChargeIndicatorType.class,
        PricingUpdateRequestIndicatorType.class,
        TransportUserReadyForExecutionIndicatorType.class,
        ContainerizedIndicatorType.class,
        ChargeIndicatorType.class,
        GovernmentAgreementConstraintIndicatorType.class,
        RequiredCurriculaIndicatorType.class,
        StatusAvailableIndicatorType.class,
        BalanceBroughtForwardIndicatorType.class,
        AnimalFoodApprovedIndicatorType.class,
        IndicationIndicatorType.class,
        AnimalFoodIndicatorType.class,
        GeneralCargoIndicatorType.class,
        MarkAttentionIndicatorType.class,
        AdValoremIndicatorType.class,
        TaxEvidenceIndicatorType.class,
        TransportServiceProviderCancellationIndicatorType.class,
        TaxIncludedIndicatorType.class,
        HumanFoodApprovedIndicatorType.class,
        ReturnableMaterialIndicatorType.class,
        CustomsImportClassifiedIndicatorType.class,
        AuctionConstraintIndicatorType.class,
        DangerousGoodsApprovedIndicatorType.class,
        RefrigerationOnIndicatorType.class,
        TransportItemTimeDeviationIndicatorType.class,
        FrozenDocumentIndicatorType.class,
        ReturnabilityIndicatorType.class,
        SplitConsignmentIndicatorType.class,
        PartialDeliveryIndicatorType.class,
        TransportServiceProviderReadyForExecutionIndicatorType.class,
        CandidateReductionConstraintIndicatorType.class,
        TransportItemConditionDeviationIndicatorType.class,
        BulkCargoIndicatorType.class,
        OrderableIndicatorType.class,
        CopyIndicatorType.class,
        MarkCareIndicatorType.class,
        ConsolidatableIndicatorType.class,
        TransportUserCancellationIndicatorType.class,
        ItemUpdateRequestIndicatorType.class,
        PrepaidIndicatorType.class,
        TransportUserCompletionIndicatorType.class,
        ThirdPartyPayerIndicatorType.class,
        ToOrderIndicatorType.class,
        CatalogueIndicatorType.class,
        PreCarriageIndicatorType.class,
        BasedOnConsensusIndicatorType.class,
        AcceptedIndicatorType.class,
        TransportServiceProviderCompletionIndicatorType.class,
        SpecialSecurityIndicatorType.class,
        UnknownPriceIndicatorType.class,
        HumanFoodIndicatorType.class,
        HazardousRiskIndicatorType.class,
        BackOrderAllowedIndicatorType.class,
        OnCarriageIndicatorType.class
})
public class IndicatorType {

    @XmlValue
    protected boolean value;

    /**
     * Gets the value of the value property.
     */
    public boolean isValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     */
    public void setValue(boolean value) {
        this.value = value;
    }

}
