//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.19 at 09:27:25 AM COT 
//


package un.unece.uncefact.data.specification.unqualifieddatatypesschemamodule._2;

import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.ValueType;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.*;
import oasis.names.specification.ubl.schema.xsd.commonextensioncomponents_2.ExtensionAgencyNameType;
import oasis.names.specification.ubl.schema.xsd.commonextensioncomponents_2.ExtensionReasonType;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:UniqueID xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;UBLUDT0000019&lt;/ccts:UniqueID&gt;
 * </pre>
 *
 *
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:CategoryCode xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;UDT&lt;/ccts:CategoryCode&gt;
 * </pre>
 *
 *
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:DictionaryEntryName xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Text. Type&lt;/ccts:DictionaryEntryName&gt;
 * </pre>
 *
 *
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:VersionID xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;1.0&lt;/ccts:VersionID&gt;
 * </pre>
 *
 *
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Definition xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;A character string (i.e. a finite set of characters) generally in the form of words of a language.&lt;/ccts:Definition&gt;
 * </pre>
 *
 *
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:RepresentationTermName xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Text&lt;/ccts:RepresentationTermName&gt;
 * </pre>
 *
 *
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:PrimitiveType xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;string&lt;/ccts:PrimitiveType&gt;
 * </pre>
 *
 *
 *
 * <p>Java class for TextType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="TextType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2>TextType">
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TextType")
@XmlSeeAlso({
        CurrentChargeTypeType.class,
        OtherInstructionType.class,
        SpecialTransportRequirmentsType.class,
        PasswordType.class,
        ChangeConditionsType.class,
        SubscriberIDTypeType.class,
        TelefaxType.class,
        SubscriberTypeIdentifierType.class,
        ReferenceType.class,
        NegotiationDescriptionType.class,
        KeywordType.class,
        RegionType.class,
        PlacardNotationType.class,
        TelecommunicationsServiceCallType.class,
        JustificationType.class,
        BuildingNumberType.class,
        OutstandingReasonType.class,
        MarkAttentionType.class,
        ClauseType.class,
        TransportServiceProviderRemarksType.class,
        PaymentNoteType.class,
        MinimumImprovementBidType.class,
        PriorityType.class,
        SpecialTermsType.class,
        ContractNameType.class,
        ValidateProcessType.class,
        HeatingTypeType.class,
        ConditionsType.class,
        ResidenceTypeType.class,
        LocationType.class,
        ValidateToolVersionType.class,
        BackorderReasonType.class,
        ConditionType.class,
        HandlingInstructionsType.class,
        CharacteristicsType.class,
        ConsumersEnergyLevelType.class,
        FrequencyType.class,
        InvoicingPartyReferenceType.class,
        HashAlgorithmMethodType.class,
        PhoneNumberType.class,
        DeliveryInstructionsType.class,
        RemarksType.class,
        MonetaryScopeType.class,
        DamageRemarksType.class,
        CustomerReferenceType.class,
        TradingRestrictionsType.class,
        TitleType.class,
        SealingPartyTypeType.class,
        XPathType.class,
        TelecommunicationsSupplyTypeType.class,
        ExtensionType.class,
        RegistrationNationalityType.class,
        ServiceNumberCalledType.class,
        ValueType.class,
        AccountingCostType.class,
        RejectReasonType.class,
        DocumentTypeType.class,
        DescriptionType.class,
        CodeValueType.class,
        ApprovalStatusType.class,
        JobTitleType.class,
        AcceptedVariantsDescriptionType.class,
        WeightType.class,
        FundingProgramType.class,
        AdditionalInformationType.class,
        SignatureMethodType.class,
        ConditionsDescriptionType.class,
        PrintQualifierType.class,
        ReplenishmentOwnerDescriptionType.class,
        CancellationNoteType.class,
        ServiceTypeType.class,
        MeterNumberType.class,
        TimezoneOffsetType.class,
        SummaryDescriptionType.class,
        ExemptionReasonType.class,
        TimingComplaintType.class,
        LossRiskType.class,
        TelecommunicationsServiceCategoryType.class,
        PaymentOrderReferenceType.class,
        CustomsClearanceServiceInstructionsType.class,
        TransportServiceProviderSpecialTermsType.class,
        TechnicalCommitteeDescriptionType.class,
        MeterReadingMethodType.class,
        ContractTypeType.class,
        PersonalSituationType.class,
        RoomType.class,
        AllowanceChargeReasonType.class,
        InstructionsType.class,
        PurposeType.class,
        OrderableUnitType.class,
        PackingMaterialType.class,
        CertificateTypeType.class,
        LineType.class,
        PostalZoneType.class,
        TransportUserSpecialTermsType.class,
        LowTendersDescriptionType.class,
        ValidateToolType.class,
        PlacardEndorsementType.class,
        ResolutionType.class,
        PriceRevisionFormulaDescriptionType.class,
        CorrectionTypeType.class,
        PostboxType.class,
        FeeDescriptionType.class,
        CountrySubentityType.class,
        LegalReferenceType.class,
        TaxExemptionReasonType.class,
        OrganizationDepartmentType.class,
        PayerReferenceType.class,
        TelephoneType.class,
        AgencyNameType.class,
        MeterNameType.class,
        MeterReadingCommentsType.class,
        TransportationServiceDescriptionType.class,
        AwardingCriteriaDescriptionType.class,
        OneTimeChargeTypeType.class,
        ConsumptionTypeType.class,
        HaulageInstructionsType.class,
        NameSuffixType.class,
        ReasonType.class,
        CarrierServiceInstructionsType.class,
        DocumentHashType.class,
        EnvironmentalDescriptionType.class,
        DistrictType.class,
        OptionsDescriptionType.class,
        TariffDescriptionType.class,
        ShippingMarksType.class,
        ContractSubdivisionType.class,
        NoteType.class,
        InformationType.class,
        RoarningPartnerNameType.class,
        LimitationDescriptionType.class,
        MovieTitleType.class,
        TransportUserRemarksType.class,
        MarkCareType.class,
        WarrantyInformationType.class,
        FloorType.class,
        MeterReadingTypeType.class,
        TierRangeType.class,
        ForwarderServiceInstructionsType.class,
        ValueQualifierType.class,
        DepartmentType.class,
        CalculationExpressionType.class,
        ExclusionReasonType.class,
        PayPerViewType.class,
        ChannelType.class,
        CanonicalizationMethodType.class,
        ProcessDescriptionType.class,
        CommentType.class,
        StatusReasonType.class,
        PlotIdentificationType.class,
        ElectronicMailType.class,
        MeterConstantType.class,
        DataSendingCapabilityType.class,
        JustificationDescriptionType.class,
        DutyType.class,
        InhouseMailType.class,
        ConsumptionLevelType.class,
        LegalFormType.class,
        RejectionNoteType.class,
        InstructionNoteType.class,
        SpecialServiceInstructionsType.class,
        PriceChangeReasonType.class,
        PriceTypeType.class,
        LoginType.class,
        ElectronicDeviceDescriptionType.class,
        DemurrageInstructionsType.class,
        PenaltyClausesType.class,
        oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.TextType.class,
        SpecialInstructionsType.class,
        ExtensionAgencyNameType.class,
        ExtensionReasonType.class
})
public class TextType
        extends un.unece.uncefact.data.specification.corecomponenttypeschemamodule._2.TextType {


}
