//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.19 at 09:27:25 AM COT 
//


package oasis.names.specification.ubl.schema.xsd.commonextensioncomponents_2;

import oasis.names.specification.ubl.schema.xsd.commonsignaturecomponents_2.UBLDocumentSignaturesType;
import org.w3c.dom.Element;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for ExtensionContentType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ExtensionContentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice minOccurs="0">
 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonSignatureComponents-2}UBLDocumentSignatures"/>
 *         &lt;group ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonSignatureComponents-2}NonSignatureNamespaceElements"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExtensionContentType", propOrder = {
        "ublDocumentSignatures",
        "any"
})
public class ExtensionContentType {

    @XmlElement(name = "UBLDocumentSignatures", namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonSignatureComponents-2")
    protected UBLDocumentSignaturesType ublDocumentSignatures;

    @XmlAnyElement
    protected Element any;

    /**
     * Gets the value of the ublDocumentSignatures property.
     *
     * @return possible object is
     * {@link UBLDocumentSignaturesType }
     */
    public UBLDocumentSignaturesType getUBLDocumentSignatures() {
        return ublDocumentSignatures;
    }

    /**
     * Sets the value of the ublDocumentSignatures property.
     *
     * @param value allowed object is
     *              {@link UBLDocumentSignaturesType }
     */
    public void setUBLDocumentSignatures(UBLDocumentSignaturesType value) {
        this.ublDocumentSignatures = value;
    }

    /**
     * Gets the value of the any property.
     *
     * @return possible object is
     * {@link Element }
     */
    public Element getAny() {
        return any;
    }

    /**
     * Sets the value of the any property.
     *
     * @param value allowed object is
     *              {@link Element }
     */
    public void setAny(Element value) {
        this.any = value;
    }

}
